DOI-USGS/snow-to-flow

- jenkins/Jenkinsfile.build
Changes made:
-----------
corrected the url for jenkins
Testing:
> change url in jenkins config

- src/components/TestFigure.vue
- src/components/VizSection.vue
- src/views/Visualization.vue
Changes made:
-----------
Description
First Cut of a customizable dynamic Viz section template
Testing:
> Reusable sections

- src/components/References.vue
- src/components/SNTLmap.vue
Changes made:
-----------
Description
Apologies for my confusing linter, it looks like I messed with your SNTLmap code, but all it did was rearrange the formatting.  What I did do is remove the **max-height** on **.map-grid** as it was causing the sections text to creep up and overlap the figure.  Removing that prevents that from happening. I'll provide screen shots.   I checked it out and it still looked like it was supposed to, let me know if this is a disastrous idea.
The extra scroll bar was from me globally importing the USWDS css like an idiot.  It is now scoped to just the Reference component and it will no longer be adding scroll bars like it wants to.
Testing:
> CSS changes

- src/views/Visualization.vue
Changes made:
-----------
Description
Easy removal of components
Testing:
> Remove THird and Fourth chapter

- Dockerfile
Changes made:
-----------
Description
Testing:
> revert node version

- src/components/SWE.vue
- src/components/Sidebar.vue
Changes made:
-----------
Description
Added Sidebar component to the line chart component.
I added it to the above Explanation div to have it control the size of the expanded sidebar as it just expands to 100% its parent size.  
Added bacon ipsum to compliment the cheese text above it.
Testing:
> Sidebar above line chart

- src/components/SNTLmap.vue
- src/components/VizSection.vue
Changes made:
-----------
Description
I successfully created a layout that stops that quirkiness we were seeing.  I switched to grid-template-areas for a more visual representation.  I believe I kept the constant scale you had as I didn't change any of that aspect.
One important thing I was seeing is you were building Desktop to Mobile in the CSS, which causes us to write unnecessary CSS in the long run.  When writing always start with mobile CSS and just use that sweet cascading feature that CSS allows us to do. 
One big example was https://github.com/USGS-VIZLAB/snow-to-flow/blob/master/src/components/SNTLmap.vue#L1892 
Since we stated on the Desktop version a left margin first we had to specifically tell mobile not to have that left margin.  We wouldn't have to do that if we did mobile …
> SNTL layout

- src/components/DiagramsHigh.vue
- src/components/DiagramsLow.vue
- src/components/DiagramsNormal.vue
- src/components/Impact.vue
- src/components/Intro.vue
- src/components/MeasuringSWE.vue
- src/components/SNTLmap.vue
- src/components/SWE.vue
- src/views/Visualization.vue
Changes made: Renamed and rearranged components to fit the story flow that CN and EB decided on after the Vizlab Crit and CDI webinar
-----------
Description
Testing:
> rearrange the story flow

- src/components/Splash.vue
Changes made:
-----------
Description
Safari was showing a missing image error, sort of.  Wasn't really showing an error but I could tell it was an issue based on its behavior.
It apparently didn't like us having the webp image used as two different source options.  Once I removed one of them it went back to working order.  Let me know if you see something off after this change.  
Testing:
> Safari Splash fix

- src/components/Splash.vue
Changes made:
-----------
Description
object-fit contain was stopping out splash images from being full screen on larger screens.  Object-fit cover to the rescue!  Also I stopped the mountains from moving on the larger screens as it was buggy, but we still get that parallax effect we desire.
Testing:
> Large screen fix for splash

- src/App.vue
- src/components/SWEanim.vue
Changes made:
-----------
the ridge plots now transition their layout between "timing", magnitude", and "by elevation". Code could be more efficient but it works.
It's cool but needs more annotations, and to have the SWE curve added on as well. Proud of my toggle button!
Testing:
> set up ridge transitions

- src/components/SWEanim.vue
Changes made:
-----------
Tried to clean up the transition code to make it more readable and concise.
Testing:
> clean up ridge code

- src/components/VizSection.vue
Changes made:
-----------
Description
We had competing h2 CSS declarations, turned the take away css to a more specific declaration and feel like the sizing is much better now.
Testing:
> smaller take away headerlines

- src/components/MeasuringSWE.vue
- src/components/SNTLmap.vue
- src/components/SWEanim.vue
- src/components/VizSection.vue
Changes made:
-----------
Description
Added a takeaway prop, so when you don't want that part of the vizsection component just set it to false on that specific component.  As a heads up I had previously done this for both the figures and figure captions.  This is probably one of the most customizable components I've ever made, kinda cool learning how to do this stuff.
Testing:
> takeAway prop added to vizsection component

- src/components/SWEanim.vue
Changes made:
-----------
Plus integrating the axis transitions and adding some annotations. It looks funny on the elevation part now, would probably be better if they were filled?
Testing:
> add swe to ridgeline

- src/views/Visualization.vue
Changes made:
-----------
Description
Replaces previous functionality with a mutation observer.  We watch the img inside the full img container, and if its src changes, we switch the caption.  So this covers clicks and arrow keys, basically any things that changes the src fires the function.  
Testing:
> footer caption bug fix

- src/components/Splash.vue
Changes made:
-----------
Description
Changed the source media queries to have a max width as I noticed it was picking the smallest media query for even the largest screen.  That being because the picture element picks the first source media query that matches, so min-width 350px is true when a screen is 2000px wide.  But min-width 350px with a max-width defeats that logic.
Noticed the lake webp isn't the best for larger screen.  I put it at the bottom so the xl image can be picked by the browser.  I noticed a twinge more detail when I did.  
Testing:
> Splash Source tweaking

- src/components/LineChart.vue
- src/components/SWEanim.vue
Changes made:
-----------
Realized the ridge mouseover wasn't working correctly. Editing this so the right line get selected and avoids glitches. Took out the fill because it was hard to see the ridges in 2/3 views
Testing:
> edits to mouseover on ridge

- public/index.html
Changes made:
-----------
Adding google analytics tags for the page. Going to go ahead and merge so I can test that it worked.
Testing:
> add UA and GA4 tags

- src/components/Sidebar.vue
Changes made:
-----------
Description
Trying to write dynamic CSS so even if we don't put a p tag in the message area the spacing should be the same.  
Testing:
> remove extra space in sidebar content

- src/components/Sidebar.vue
Changes made:
-----------
Description
Sidebar buttons on Edge and firefox were cutting off the text occasionally due to a JS function timing issue.  Switching to a window load solves the problem.  Also have the button fades in after load to avoid the awkward huge button to regular size also based on the JS running.  
In short, button text will not be cut off any longer.
Testing:
> Sidebar bug

- src/components/SWE.vue
Changes made:
-----------
Fixed a link target that had a typo.
Testing:
> missing "t" in target

- src/components/LineChart.vue
Changes made:
-----------
Description
Testing:
> fix inline buttons in line chart

- src/components/Splash.vue
Changes made:
-----------
Description
Testing:
> omit people on mobile

- src/components/Splash.vue
Changes made:
-----------
Description
Testing:
> remove people from splash

- README.md
Changes made:
-----------
Description
Testing:
> fix readme image url
